base_url = "https://alexnav73.github.io"
compile_sass = true
build_search_index = true

# Theme settings
theme = "after-dark"
taxonomies = [
   { name = "categories", feed = true },
   { name = "tags", feed = true },
]

[markdown]
highlight_code = true

[extra]
author = "Aliaksandr Navitski"
after_dark_menu = [
    { url = "$BASE_URL", name = "Home" },
    { url = "$BASE_URL/categories", name = "Categories" },
    { url = "$BASE_URL/tags", name = "Tags" },
]
after_dark_title = "Notes "
